on:
  push:
     branches:
       - main
       - master
       - ajout_ci

name: rendersite

jobs:
  website:
    name: Render-website
    runs-on: macOS-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@master

      - name: Install pandoc
        run: |
          brew install pandoc

      - name: Cache Renv packages
        uses: actions/cache@v2
        with:
          path: $HOME/.local/share/renv
          key: r-${{ hashFiles('renv.lock') }}
          restore-keys: r-

      - name: Build site
        run: Rscript -e 'rmarkdown::render_site(encoding = 'UTF-8', quiet = TRUE)'
        
      - uses: actions/upload-artifact@v1
        with:
          name: docs
          path: docs/
  
# Need to first create an empty gh-pages branch
# see https://pkgdown.r-lib.org/reference/deploy_site_github.html
# and also add secrets for a GH_PAT and EMAIL to the repository
# gh-action from Cecilapp/GitHub-Pages-deploy
  checkout-and-deploy:
   runs-on: ubuntu-latest
   needs: website
   steps:
     - name: Checkout
       uses: actions/checkout@master
     - name: Download artifact
       uses: actions/download-artifact@v1.0.0
       with:
         # Artifact name
         name: docs # optional
         # Destination path
         path: docs # optional
     - name: Deploy to GitHub Pages
       uses: Cecilapp/GitHub-Pages-deploy@master
       env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }} # https://github.com/settings/tokens
       with:
          build_dir: docs                          # "_site/" by default
          email: ${{ secrets.EMAIL }}               # must be a verified email
        